BE.Web/Models/Api/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models.Api
{
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

BE.Web/Models/Api/PremiumAds.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models.Api
{
    public class PremiumAds
    {
        public int Id { get; set; }
        public int LocationsID { get; set; }
        public int SubCategoryID { get; set; }
        public Location Location { get; set; }
        public SubCategory SubCategory { get; set; }
        public DateTime PremiumStart { get; set; }
        public DateTime PremiumEnd { get; set; }
    }
    
}

BE.Web/Models/Api/SubCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models.Api
{
    public class SubCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

BE.Web/Models/ErrorViewModel.cs
using System;

namespace BE.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BE.Web/Models/Settings.cs
using System;

namespace GloboTicket.Web.Models
{
    public class Settings
    {
        public string BasketIdCookieName => "BasketId";
        public  Guid UserId => Guid.Parse("{E455A3DF-7FA5-47E0-8435-179B300D531F}");
    }
}

BE.Web/Models/View/AddNewModel.cs
using BE.Web.Models.Api;
using System;
using System.Collections.Generic;

namespace BE.Web.Models.View
{
    public class AddNewModel
    {
        public IEnumerable<Location> Locations { get; set; }

        public IEnumerable<SubCategory> SubCategories { get; set; }

        public string SelectedLocationId { get; set; }

        public string SelectedSubcategoryId { get; set; }

        public DateTime PremiumStart { get; set; } = DateTime.Now;

        public DateTime PremiumEnd { get; set; } = DateTime.Now.AddDays(1);
    }
}

BE.Web/Models/View/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models.View
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BE.Web/Models/View/PremiumAdListModel.cs
using BE.Web.Models.Api;
using System.Collections.Generic;

namespace BE.Web.Models.View
{
    public class PremiumAdListModel
    {
        public IEnumerable<PremiumAds> PremiumAds { get; set; }
    }
}

BE.Web/Controllers/PremiumAdsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BE.Web.Models.Api;
using BE.Web.Models.View;
using BE.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace BE.Web.Controllers
{
    public class PremiumAdsController : Controller
    {
        private readonly IPremiumAdsService premiumAdsService;
        public IEnumerable<Location> locations;
        public IEnumerable<SubCategory> subcategories;
        public PremiumAdsController(IPremiumAdsService premiumAdsService)
        {
            this.premiumAdsService = premiumAdsService;
        }
        public async Task<IActionResult> Index()
        {
            return View(new PremiumAdListModel { PremiumAds = await premiumAdsService.GetPremiumAds() });
        }

        public async Task<IActionResult> AddNew()
        {
            locations = await premiumAdsService.GetLocations();
            //Subcategories can be loaded as per the location dropdown change to make it more robust. 
            subcategories = await premiumAdsService.GetSubCategories(); 


            return View(new AddNewModel {
                Locations = locations, 
                SubCategories = subcategories,
                SelectedLocationId = string.Empty 
            });
        }

        [HttpPost]
        public  async Task<IActionResult> AddNewPremium(AddNewModel addNewModel)
        {
            await premiumAdsService.CreatePremiumAd(new PremiumAds
            {
                LocationsID = Convert.ToInt32(addNewModel.SelectedLocationId),
                SubCategoryID = Convert.ToInt32(addNewModel.SelectedSubcategoryId),
                PremiumStart = addNewModel.PremiumStart,
                PremiumEnd = addNewModel.PremiumEnd,
            });
            return RedirectToAction("Index", new { categoryId = addNewModel.SelectedLocationId });
        }

    }
}

BE.Web/Views/PremiumAds/AddNew.cshtml
@model BE.Web.Models.View.AddNewModel

@{
    var categoryListItems = Model.Locations.Select(c =>
        new SelectListItem { Value = c.Id.ToString(), Text = c.Name }
    ).ToList();
    categoryListItems.Insert(0, new SelectListItem { Text = "All" });

    var subCategories = Model.SubCategories.Select(c =>
        new SelectListItem { Value = c.Id.ToString(), Text = c.Name }
    ).ToList();
    subCategories.Insert(0, new SelectListItem { Text = "All" });
}
<div class="row mt-5 mb-3">
    @using (Html.BeginForm("AddNewPremium", "PremiumAds", FormMethod.Post))
    {

        @Html.DropDownListFor(m => m.SelectedLocationId,
          categoryListItems)

        @Html.DropDownListFor(m => m.SelectedSubcategoryId,
          subCategories)

        @Html.TextBoxFor(m => m.PremiumStart, "{0:dd/M/yyyy}", new { Style = "height:40px;margin-right: 10px;" })

        @Html.TextBoxFor(m => m.PremiumEnd, "{0:dd/M/yyyy}", new { Style = "height:40px;" })

        <button type="submit" class="filterButton">Save</button>
    }
</div>

BE.Web/Views/PremiumAds/Index.cshtml
@model BE.Web.Models.View.PremiumAdListModel

<div class="row mt-5 mb-3">
    <form asp-action="AddNew" method="post">
        <button type="submit" class="filterButton">Add New</button>
    </form>
</div>

<div class="row">
    @if (Model.PremiumAds.Count() == 0)
    {
        <text>No events were found.</text>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">AdId</th>
                    <th scope="col">Location Name</th>
                    <th scope="col">Subcategory Name</th>
                    <th scope="col">Premium Start</th>
                    <th scope="col">Premium End</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var premiumAd in Model.PremiumAds)
                {
                    <tr>
                        <th scope="row">@premiumAd.Id</th>
                        <td>@premiumAd.Location.Name</td>
                        <td>@premiumAd.SubCategory.Name</td>
                        <td>@premiumAd?.PremiumStart.ToString(string.Format("dd/MM/yyyy"))</td>
                        <td>@premiumAd?.PremiumEnd.ToString(string.Format("dd/MM/yyyy"))   </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

BE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BE.Web Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Premium Ads</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>